name: ${name}
version: ${version}
api-version: 1.17
authors: [w0819, dolphin2410]
libraries:
  - io.github.monun:tap:4.1.10
  - io.github.monun:kommand:2.6.6
  - net.projecttl:InventoryGUI-api:4.1.8
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0
  - io.github.monun:heartbeat-coroutines:0.0.1
  - io.github.dolphin2410:worldgen:0.0.1
main: com.github.w0819.plugin.UHCPlugin
description: Hypixel's UHCSystem Implementation
website: https://github.com/w0819/UHC_System

