name: ${name}
version: ${version}
api-version: 1.18
authors: [w0819, dolphin2410]
libraries:
  - io.github.monun:tap-core:4.4.0
  - io.github.monun:kommand-core:2.10.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0
  - io.github.monun:heartbeat-coroutines:0.0.3
main: com.github.w0819.plugin.UHCPlugin
description: Hypixel's UHCSystem Implementation
website: https://github.com/w0819/UHC_System
