name: Recipe
version: 0.0.1
api-version: 1.17
author: w0819
libraries:
  - io.github.monun:tap-api:4.1.9
  - io.github.monun:kommand-api:2.6.6
  - net.projecttl:InventoryGUI-api:4.1.8
main: com.github.w0819.main.Main